cumulusci/core/tests/mdapisrc/ccitest/objects/SampleObject__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Sample_Field__c</fullName>
        <label>Sample Field</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>SampleObject</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SampleObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cumulusci/core/tests/mdapisrc/ccitest/classes/SamplePage_CTRL_TEST.cls
@isTest
public with sharing class SamplePage_CTRL_TEST {

    public static testmethod void getSamplesTest() {
    	SampleObject__c sample = new SampleObject__c(Sample_Field__c = 'MyData');
    	insert  sample;
    	
		Test.startTest();

		SamplePage_CTRL controller = new SamplePage_CTRL();
    	List<SampleObject__c> samples = controller.getSamples();
    	
		Test.stopTest();

		System.assertEquals(1, samples.size());
    	System.assertEquals('MyData', samples[0].Sample_Field__c);
    }
}